name: Daily Activation and Dependency Check

on:
  schedule:
    - cron: '0 0 * * *'  # Exécute tous les jours à minuit UTC

jobs:
  dependabot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Set up Docker
        uses: docker/setup-buildx-action@v1

      - name: Dependabot
        uses: dependabot/dependabot-core@v0.157.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          directory: './'
          update_schedule: 'daily'
          package_manager: 'gomod,docker'

      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Update dependencies"
          git push
