name: configure and Daily Activation and Dependency Check
on:
  schedule:
    - cron: '0 0 * * *'  # Exécute tous les jours à minuit UTC

jobs:
  check-dependencies:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Verify Go dependencies
        run: go mod verify

      - name: Set up Docker
        uses: docker/setup-buildx-action@v1

      - name: Verify Docker
        run: docker version
